apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-job-wrapper.fullname" . }}-cronjob-admin-role
  labels:
  {{- include "k8s-job-wrapper.labels" . | nindent 4 }}
rules:
- apiGroups:
  - pixiv.net
  resources:
  - cronjobs
  verbs:
  - '*'
- apiGroups:
  - pixiv.net
  resources:
  - cronjobs/status
  verbs:
  - get
