# This rule is not used by the project k8s-job-wrapper itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to pixiv.net resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-job-wrapper
    app.kubernetes.io/managed-by: kustomize
  name: job-viewer-role
rules:
- apiGroups:
  - pixiv.net
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pixiv.net
  resources:
  - jobs/status
  verbs:
  - get
