/*
Copyright 2026 pixiv Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package utils

import (
	"encoding/json"
	"fmt"
	"slices"
	"strings"

	batchv1 "k8s.io/api/batch/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

const (
	PodProfileResource = "podprofiles.pixiv.net"
	JobResource        = "jobs.pixiv.net"
	CronJobResource    = "cronjobs.pixiv.net"
)

// Check for the value of the resource.
func EnsureResourceValue(namespace, resource, name, jsonPath, want string) {
	GinkgoHelper()
	By(fmt.Sprintf("making ensure the %s %s value at %s is %s", resource, name, jsonPath, want))
	Eventually(func(g Gomega) {
		out, err := Run(KubectlCmd("-n", namespace, "get", resource, name, "-o", "jsonpath="+jsonPath))
		g.Expect(err).To(Succeed())
		g.Expect(out).To(Equal(want))
	}).To(Succeed())
}

// Check for the existence of a PodProfile.
func EnsurePodProfile(namespace, name string) {
	GinkgoHelper()
	By(fmt.Sprintf("making ensure the PodProfile %s is created", name))
	ensurePodProfile := func() error {
		_, err := Run(KubectlCmd("-n", namespace, "get", PodProfileResource, name))
		return err
	}
	Eventually(ensurePodProfile).To(Succeed())
}

func EnsureCustomResourceStatus(namespace, resource, name string) {
	GinkgoHelper()
	By(fmt.Sprintf("making ensure the %s %s is successfully created", resource, name))
	ensure := func(g Gomega) {
		output, err := Run(
			KubectlCmd("-n", namespace, "get", resource, name, "-o", "jsonpath={.status.conditions}"),
		)
		g.Expect(err).To(Succeed(), fmt.Sprintf("Failed to get the %s", resource))
		var conditions []metav1.Condition
		g.Expect(json.Unmarshal([]byte(output), &conditions)).To(Succeed())
		g.Expect(conditions).Should(HaveLen(2), fmt.Sprintf("Invalid %s conditions", resource))
		d := map[string]metav1.Condition{}
		for _, c := range conditions {
			d[c.Type] = c
		}
		available, exist := d["Available"]
		g.Expect(exist).To(BeTrue())
		g.Expect(available.Status).To(Equal(metav1.ConditionTrue))
		g.Expect(available.Reason).To(Equal("OK"))

		degraded, exist := d["Degraded"]
		g.Expect(exist).To(BeTrue())
		g.Expect(degraded.Status).To(Equal(metav1.ConditionFalse))
		g.Expect(degraded.Reason).To(Equal("OK"))
	}
	Eventually(ensure).To(Succeed())
}

// Check for the existence of a Job.
func EnsureJob(namespace, name string) {
	GinkgoHelper()
	EnsureCustomResourceStatus(namespace, JobResource, name)
}

// Check for the existence of a CronJob.
func EnsureCronJob(namespace, name string) {
	GinkgoHelper()
	EnsureCustomResourceStatus(namespace, CronJobResource, name)
}

func BatchCronJobName(pixivNetCronJobName string) string {
	return pixivNetCronJobName + "-pxvcjob"
}

// Check for the existence of a batch CronJob spawned from CronJob.
func EnsureBatchCronJob(namespace, pixivNetCronJobName string) {
	GinkgoHelper()
	name := pixivNetCronJobName
	By(fmt.Sprintf("making ensure the batch CronJob %s generated by the CronJob %s", BatchCronJobName(name), name))
	Eventually(func() error {
		_, err := Run(
			KubectlCmd("-n", namespace, "get", "cronjob", BatchCronJobName(name)),
		)
		return err
	}).To(Succeed())
}

// Verify that the batch job status is successful.
func EnsureBatchJobStatusCompleted(namespace, batchJobName string) {
	GinkgoHelper()
	By(fmt.Sprintf("making ensure the batch Job %s is completed successfully", batchJobName))
	Expect(batchJobName).ShouldNot(BeEmpty(), "batchJobName should not be empty")

	ensureBatchJobStatusCompleted := func(g Gomega) {
		output, err := Run(KubectlCmd(
			"get", "-n", namespace, "job", batchJobName, "-o", "jsonpath={.status.conditions}"),
		)
		g.Expect(err).To(Succeed(), "Failed to get the batch Job conditions")
		var conditions []batchv1.JobCondition
		g.Expect(json.Unmarshal([]byte(output), &conditions)).To(Succeed())
		d := map[string]batchv1.JobCondition{}
		for _, c := range conditions {
			d[string(c.Type)] = c
		}
		successCriteriaMet, exist := d[string(batchv1.JobSuccessCriteriaMet)]
		g.Expect(exist).To(BeTrue())
		g.Expect(successCriteriaMet.Status).To(Equal(corev1.ConditionTrue))
		g.Expect(successCriteriaMet.Reason).To(Equal(batchv1.JobReasonCompletionsReached))

		complete, exist := d[string(batchv1.JobComplete)]
		g.Expect(exist).To(BeTrue())
		g.Expect(complete.Status).To(Equal(corev1.ConditionTrue))
		g.Expect(complete.Reason).To(Equal(batchv1.JobReasonCompletionsReached))
	}
	Eventually(ensureBatchJobStatusCompleted).To(Succeed())
}

func EnsureBatchCronJobWorking(namespace, name string) {
	GinkgoHelper()
	By(fmt.Sprintf("making ensure the batch CronJob %s is working", BatchCronJobName(name)))
	Eventually(func(g Gomega) {
		output, err := Run(
			KubectlCmd("-n", namespace, "get", "cronjob", BatchCronJobName(name), "-o",
				"jsonpath={.status.lastSuccessfulTime}}"),
		)
		g.Expect(err).To(Succeed())
		g.Expect(output).ShouldNot(BeEmpty())
	}).Should(Succeed())
	By(fmt.Sprintf("get the generated batch Job by the batch CronJob %s", BatchCronJobName(name)))
	var batchJobName string
	// Batch Jobs spawned from batch CronJob have batch CronJob as their ownerReferences.
	// Output is like: name\towner1 owner2
	Eventually(func(g Gomega) {
		output, err := Run(
			KubectlCmd("-n", namespace, "get", "job", "-o",
				`jsonpath={range .items[*]}{.metadata.name}{"\t"}{range .metadata.ownerReferences[*]}{.name}{" "}{end}{"\n"}{end}`), //nolint:lll
		)
		g.Expect(err).To(Succeed())
		lines := strings.Split(strings.TrimSpace(output), "\n")
		g.Expect(lines).ShouldNot(BeEmpty())
		// Dictionary: name of batch Job -> owner names
		nameToOwners := map[string][]string{}
		for _, line := range lines {
			xs := strings.Split(line, "\t")
			if len(xs) != 2 {
				continue
			}

			owners := []string{}
			for x := range strings.SplitSeq(xs[1], " ") {
				s := strings.TrimSpace(x)
				if s != "" {
					owners = append(owners, s)
				}
			}
			nameToOwners[xs[0]] = owners
		}
		By(fmt.Sprintf("find the batch Job with owner %s", BatchCronJobName(name)))
		for bjName, owners := range nameToOwners {
			if slices.Contains(owners, BatchCronJobName(name)) {
				// A job with owner cronjob was found.
				batchJobName = bjName
				break
			}
		}
		g.Expect(batchJobName).ShouldNot(BeEmpty())
	}).Should(Succeed())

	By(fmt.Sprintf("making ensure the batch Job %s generated by the batch CronJob %s is completed",
		batchJobName, BatchCronJobName(name)))
	EnsureBatchJobStatusCompleted(namespace, batchJobName)
}

// Get a list of batch Job names spawned from a Job.
func ListBatchJobs(namespace, jobName string) ([]string, error) {
	GinkgoHelper()
	output, err := Run(
		KubectlCmd(
			"-n", namespace, "get", "job",
			"-o", "jsonpath={.items[*].metadata.name}",
			"-l", "app.kubernetes.io/created-by=pixiv-job-controller",
			"-l", fmt.Sprintf("jobs.pixiv.net/name=%s", jobName),
		),
	)
	if err != nil {
		return nil, err
	}
	return strings.Split(output, " "), nil
}

// Verify that the batch Job spawned from the Job succeeds.
func EnsureBatchJobCompleted(namespace, jobName string) {
	GinkgoHelper()
	By(fmt.Sprintf("making ensure the batch Job generated by the Job %s is successfully completed", jobName))
	var name string
	ensureBatchJob := func(g Gomega) {
		names, err := ListBatchJobs(namespace, jobName)
		g.Expect(err).To(Succeed(), "Failed to get generated batch Jobs")
		g.Expect(names).Should(HaveLen(1))
		name = names[0]
		g.Expect(name).ShouldNot(BeEmpty())
	}
	Eventually(ensureBatchJob).Should(Succeed()) // Wait until the batch job name is obtained
	EnsureBatchJobStatusCompleted(namespace, name)
}

// Verify that the Job has created only one batch Job.
// If so, return the name of that batch Job.
func EnsureOnlyOneBatchJobCreated(namespace, jobName string) string {
	GinkgoHelper()
	By(fmt.Sprintf("making ensure the Job %s created only one batch Job", jobName))
	names, err := ListBatchJobs(namespace, jobName)
	Expect(err).To(Succeed())
	Expect(names).Should(HaveLen(1))
	return names[0]
}

// Get a list of Pod names spwned from a batch Job.
func ListBatchJobPods(namespace, batchJobName string) ([]string, error) {
	output, err := Run(
		KubectlCmd(
			"-n", namespace, "get", "pod",
			"-o", "jsonpath={.items[*].metadata.name}",
			"-l", "job-name="+batchJobName,
		),
	)
	if err != nil {
		return nil, err
	}
	return strings.Split(output, " "), nil
}

// Verify that the batch Job created only one Pod.
// If so, return the name the Pod.
func EnsureOnlyOneBatchJobManagedPodCreated(namespace, batchJobName string) string {
	GinkgoHelper()
	By(fmt.Sprintf("making ensure the batch Job %s created only one Pod", batchJobName))
	names, err := ListBatchJobPods(namespace, batchJobName)
	Expect(err).To(Succeed())
	Expect(names).Should(HaveLen(1))
	return names[0]
}
