name: Kind Setup
description: Create kind cluster
inputs:
  node_image:
    description: "The Docker image for the cluster nodes"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install kind
      shell: bash
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind
        kind version
    - name: Create kind cluster
      shell: bash
      run: kind create cluster --image '${{ inputs.node_image }}'
