name: Kind Setup
description: Create kind cluster
inputs:
  node-image:
    description: "The Docker image for the cluster nodes"
    required: true
runs:
  using: "composite"
  steps:
    # helm/kind-action failed to load local container image for unknown reason
    # so use kind binary directly
    - name: Create kind cluster
      shell: bash
      run: ./hack/tools.sh kind create cluster --image "$NODE_IMAGE"
      env:
        NODE_IMAGE: ${{ inputs.node-image }}
