name: Kind Setup
description: Create kind cluster
inputs:
  node_image:
    description: "The Docker image for the cluster nodes"
    required: true
  kubectl_version:
    description: "The kubectl version to use"
    required: true
runs:
  using: "composite"
  steps:
    - name: Create kind cluster
      uses: helm/kind-action@v1.12.0
      with:
        cluster_name: kind
        node_image: '${{ inputs.node_image }}'
        kubectl_version: '${{ inputs.kubectl_version }}'
