name: Buildx Setup
description: Setup docker buildx
runs:
  using: "composite"
  steps:
    - uses: docker/setup-docker-action@v4
      with:
        daemon-config: |
          {
            "debug": true,
            "features": {
              "containerd-snapshotter": true
            }
          }
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-config-inline: |
          [registry."docker.io"]
            mirrors = ["mirror.gcr.io"]
