name: Buildx Setup
description: Setup docker buildx
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
      with:
        buildkitd-config-inline: |
          [registry."docker.io"]
            mirrors = ["mirror.gcr.io"]
