name: Check
permissions: {}
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  lint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup common
        uses: ./.github/actions/common
      - name: Setup go
        uses: ./.github/actions/setup-go
        with:
          version: '${{ env.GO_VERSION }}'
      - name: Lint
        run: make lint
