name: Check
on:
  pull_request:
  push:
    branches:
      - 'main'
permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup common
        uses: ./.github/actions/common
      # - name: Setup go
      #   uses: ./.github/actions/setup-go
      #   with:
      #     version: '${{ env.GO_VERSION }}'
      - name: Install Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: '${{ env.GO_VERSION }}'
          check-latest: true
      - name: Lint
        run: make lint
