name: E2E Test
permissions: {}
on:
  pull_request:
  push:
    branches:
      - 'main'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: E2E
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: "false"
      - name: Setup common
        uses: ./.github/actions/common
      - name: Cache docker local
        id: cache-docker-local
        uses: ./.github/actions/cache-docker-local
        with:
          path: ${{ env.DOCKER_CACHE_DIR }}
      - name: Setup buildx
        uses: ./.github/actions/setup-buildx
      - name: Setup go
        uses: ./.github/actions/setup-go
      - name: Setup kind
        uses: ./.github/actions/setup-kind
        with:
          node-image: '${{ env.KIND_NODE_IMAGE }}'
      - name: Build
        run: make docker-build
      - name: E2E test
        run: make test-e2e
