name: Test
permissions: {}
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: "false"
      - name: Setup common
        uses: ./.github/actions/common
      - name: Setup go
        uses: ./.github/actions/setup-go
        with:
          version: '${{ env.GO_VERSION }}'
      - name: Test
        run: make test
